kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  serviceName: kafka-service
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:latest
        ports:
          - containerPort: 9092
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-service:2181"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://:9092
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://0.0.0.0:9092
        volumeMounts:
          - name: kafka-storage
            mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi