apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit-deployment
spec:
  selector:
    matchLabels:
      app: limit
  template:
    metadata:
      labels:
        app: limit
    spec:
      containers:
        - name: limit
          image: avusar/limit
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_LIQUIBASE_CONTEXTS
              value: "prod, dev"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/bankDB"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: SPRING.DATASOURCE.PASSWORD
              valueFrom:
                secretKeyRef:
                  name: persistance-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
            - name: SPRING_DATASOURCE_PLATFORM
              value: "postgres"
            - name: jwt.secret
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: kafka.server
              value: "kafka-service:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: limit
spec:
  selector:
    app: limit
  ports:
    - port: 8080
      targetPort: 8080